---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/v1/metrics
    prometheus.io/scrape: "true"
  name: crispy-robot-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: crispy-robot-web
  type: ClusterIP
